server:
  port: 8081

# 数据库配置
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
#    url: jdbc:mysql://121.41.166.91:3306/MFM?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8
    url: jdbc:mysql://localhost:3306/MFM?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8
    username: root
    password: rootroot
    hikari:
      connection-test-query: SELECT 1 # 自动检测连接
      connection-timeout: 60000 #数据库连接超时时间,默认30秒
      idle-timeout: 500000 #空闲连接存活最大时间，默认600000（10分钟）
      max-lifetime: 540000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      maximum-pool-size: 12 #连接池最大连接数，默认是10
      minimum-idle: 10 #最小空闲连接数量
      pool-name: SPHHikariPool # 连接池名称

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1024MB

  data:
    redis:
      port: 6379
      host: localhost
      database: 0

  rabbitmq:
    host: localhost
    port: 5672
    username: duzhijun
    password: duzhijun

#用于打印框架生成的sql语句，便于调试
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: mfm

alipay:
  enable: true
  app-id: 9021000140677620
  merchant-private-key: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCWOKeVrjG1xmAxiQTbLeg5WPZ1WQRmAAy4qqwdF0VtbC46Mu7hySKesiT/AomUrlD17x2yWaXb7vgg0AGkE7F5i8B/97Hvs+iF5A0qE8ooYnaQy9ThROwbEPjksEOu+r9N0sPnGEkvMIkQ6MpxaukbvPucqhnUatXSsDAkCgdYrS6CbBAfSPYApy7Vnp6Sm3s6d8WrG4YH/m1LyY0gFpP5t9yoovqltYDWPAK/0zB8719z47ahiRk26euuKqBXDQQnrbICyzcOdWKmEhNCInyde5ch+UGx8/wRD6Bf6O4ts2p0Xl0yelrr6NfZvWBZSkbRYkW7yEztrYPJP0szmq0JAgMBAAECggEBAIkCYS6ucp5EsSVcv/Yb16q+TgLXTqCtOO0QlOvvdp4HRd5E6AU8SnwNJJsFOHBH0IWOMjqhcxm1yc87h9ObNooSAV91jW9/WfsL9UnEROQyccs8bQuMrf89qpQBg6nK/sI/Effq+Yy1qr2mZEWvaa6n3aCUr/xB+IUxtqaYEv03iPT3xQ4dnzxJJ+lX2faifIeBg+8Fpx2/lWNZL8sIB9CsA+yLU2O/Ac7cZ1U/awiPu8eep0h7ZhaPSNYuHKL5FqFYJdtqc7UKliU47puUYkxOEMyZsa0fjpTbSilIArBP+5TBOV37MrkAM+sxhcEYYi0gg8KFykZK5tGpme4wS8UCgYEAxF/1MHUIU4Cm/FtfMBOL5F8af7agZjkNfswuT3ISHpA1JuEKDKqIr/pYXyrCOX/7DZZGbpdBwrzwPYAviUdbEMuumMWFyEsAsSIzRSygwsU08r39hV7gjxqO+YqR60+ilNrgAFl5QSLvUjZ+pI9DGw7MopMri4ruUhDIFPI38X8CgYEAw9U5VUGKvnniFncl4yR7BSUmQgZ6tmajLPBP3J/sWdyZwO8k8yRGrGdZ9gU9b9nNM+97DIDeUKovnOVwErw5INZZuA8AhmlROeZP0EU2svwpGk2+m/1YPElLljwbS5bVn8g7wCzUm3ToFAdP+xvX1Mo5+ukDfU8kterhvuw2FXcCgYEAgk3mJaxSxQ3mQCflRsKBnh0ZOUuWrZ4H/W5BAIiBy3QHQPAsufDi2Fq3DxcRYBQzI3Xm8HU/tpemljib0mzd2Yw+I7NVrW1PXTqDaNBPME6pbrVxJ3Gocmy+GInBf7INANcnsjOsyPMEeLoeWNWTQr4UPYCIcYTT1PK7wWJkisMCgYEAiPd/8wY1UQWUQJwy7owcUrvp5zH678oXhJ3LbYaY2zz0eMGKOVh86aYbgHunvaw63oE3scYMN6TgSj8axK/K0RG6jIZJmrjca7+OwR83o7XD1bbcguONrBSjfj8p5BNp9Cgqyj1Qsi3xB9kZcorFyPlr1fbVTvZkuau/GjbBmP8CgYAeP3b6CjSNsbQmExTzLLH0Kp/F4XrQb9uXNNCl2pwng2gFqvTm7aS39CGKLA7ZjKM6BC1IdaIHKKjuLV5JBv3GZxJF5hbFD05YxodOOVVJHYHlgldkSYfJryb2fjy+q7Hd6AuBOeeDdbhGT8cB7gDIPB/RKCQoIlyDXLzgZ6ve3A==
  alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiNmbQODo8EoGGcn+B6lvTRlcaCd7bDcKwkeEON+gvPZ3nl61/tq52Qay9KhpiFk64EukW62w6iP+0AYs7GsocKdZDdQs9E03iQTmelj8++wczKCi/lKL7IMiOGAPYr1yH8pOeoysuLYlnkSc3Tr8ArfZzBUJG+w/uCenrZMwiIxBqqXbCNDVstploCV3oDDdxHsVyDWEJWrtdkbNYc92k6DD3hxizIFa5c3LDcPCSYVLMbZNtnbAvN46CniKARuEzJM37HNbeHjknSaOF0qyC5qwpr12KTN8FBG8qz8Rpac/M71UommgaJNYz7LI3NDTzdCuVM7JtPqCfIw4yPxU1QIDAQAB
  server-url: https://openapi.alipay.com/gateway.do
  format: json
  charset: utf-8
  sign-type: RSA2
